Algoritmo "ex3"

Var
l1,l2,l3,p:real


Inicio
escreval ("Insira os dados em centimetros:")

escreval ("Insira o valor de um lado qualquer de seu triângulo")
leia (l1)

escreval ("Insira o valor de um lado diferente do último inserido")
leia (l2)

escreval ("Insira o valor de um lado diferente dos últimos inseridos")
leia (l3)

p<-l1+l2+l3

escreval ("O perimetro será de:",p,"cm")
Fimalgoritmo