algoritmo "Exercicio 3 pseudo código"

var
n1, n2, sub : real

inicio
Escreval ("Insira o primeiro numero")
leia (n1)
Escreval ("Insira o segundo numero")
leia (n2)

sub <- (n1-n2)

se (sub<0) entao
escreval ("O resultado é negativo")
senao
     se (sub = 0) entao
     escreval ("O resultado é neutro")
     senao
          se (sub>0)entao
          escreval ("O resultado é positivo")
          Fimse
     Fimse
fimse



fimalgoritmo



